//
// Created by Emil Priv on 03/02/2023.
//

#ifndef AUTOMATIC_BARGAIN_HUNTING_STORE_DATA_SCRAPE_H
#define AUTOMATIC_BARGAIN_HUNTING_STORE_DATA_SCRAPE_H

#endif //AUTOMATIC_BARGAIN_HUNTING_STORE_DATA_SCRAPE_H

void testfile(void);